behaviors:
  TetrisPPO:
  
    trainer_type: ppo
    max_steps: 1.0e7
    time_horizon: 64
    summary_freq: 10000
    keep_checkpoints: 5
    checkpoint_interval: 50000
    threaded: false
    init_path: null

    hyperparameters:
      # Hyperparameters common to PPO and SAC
      batch_size: 512
      buffer_size: 50000
      learning_rate: 0.001
      learning_rate_schedule: constant

      # SAC-specific hyperparameters
      # buffer_init_steps: 10000
      # tau: 0.005
      # steps_per_update: 1
      
      # PPO-specific hyperparameters
      beta: 1e-4
      epsilon: 0.1


    # Configuration of the neural network (common to PPO/SAC)
    network_settings:
      vis_encode_type: simple
      normalize: false
      hidden_units: 128
      num_layers: 2
      # memory
      memory:
        sequence_length: 64
        memory_size: 256

    reward_signals:
      # environment reward (default)
      extrinsic:
        strength: 1.0
        gamma: 0.99
      
      # GAIL
      #gail:
      #  strength: 0.5
      #  demo_path: Demos/TetrisDemo.demo

    # BC
    #behavioral_cloning:
    #  strength: 0.5
    #  demo_path: Demos/TetrisDemo.demo
    #  batch_size: 512
    #  num_epoch: 3
    #  samples_per_update: 0